# 第一阶段：使用 Maven 镜像构建项目
FROM maven:latest AS build
# 设置工作目录
WORKDIR /app
# 复制 Maven 项目的 pom.xml 和 src 目录
COPY pom.xml .
COPY src ./src
# 使用 Maven 构建项目
RUN mvn clean package

FROM openjdk:24-jdk
# 设置工作目录
WORKDIR /app
# 复制已经编译好的jar文件到容器中
COPY --from=build /app/target/*.jar ./app.jar
# 暴露应用端口（注意，这里是应用内部运行的端口，与Kubernetes的targetPort对应）
EXPOSE 8081
# 启动Spring Boot应用
CMD ["java", "-jar", "app.jar"]